"""Hook handlers — entry points invoked by Claude Code via settings.json.

All three handlers are fail-open: any error → exit 0 → allow the operation.
Memory is a quality-of-life layer; it must never block real work.

- ``stop``   : regen MEMORY.md from frontmatter (Stop event)
- ``guard``  : block Write/Edit on MEMORY.md (PreToolUse)
- ``inject`` : surface relevant prior lessons when Reading a file (PreToolUse)
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from .store import Store
from . import index_gen
from . import paths


def _autodetect_memory_dir() -> Path | None:
    return paths.resolve_memory_dir()


def _read_stdin_json() -> dict:
    try:
        raw = sys.stdin.read()
    except Exception:
        return {}
    if not raw.strip():
        return {}
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return {}


SKIP_REGEN_SENTINEL = ".ccmemory-skip-regen"


def stop_handler() -> int:
    _read_stdin_json()  # drain
    d = _autodetect_memory_dir()
    if not d:
        return 0
    sentinel = d / SKIP_REGEN_SENTINEL
    if sentinel.exists():
        sys.stderr.write(f"[ccmemory] MEMORY.md regen skipped ({sentinel.name} present)\n")
        return 0
    try:
        result = index_gen.write(d)
        sys.stderr.write(f"[ccmemory] MEMORY.md regen: {result['bytes']}B truncated={result['truncated']}\n")
    except Exception as e:
        sys.stderr.write(f"[ccmemory] regen failed (fail-open): {e}\n")
    return 0


def guard_handler() -> int:
    """Block Write/Edit on MEMORY.md — it's generated, not authored."""
    payload = _read_stdin_json()
    tool_name = payload.get("tool_name") or payload.get("toolName") or ""
    tool_input = payload.get("tool_input") or payload.get("toolInput") or {}
    path = tool_input.get("file_path") or tool_input.get("path") or ""

    if tool_name in ("Write", "Edit", "NotebookEdit") and path.endswith("/MEMORY.md"):
        msg = (
            "MEMORY.md is generated by ccmemory from each memory file's "
            "frontmatter `description:` field. Direct edits get clobbered on "
            "the next Stop-hook regen.\n\n"
            "To remember something: write a new .md file in this directory "
            "with YAML frontmatter (name, description, metadata.type). The "
            "Stop hook regenerates MEMORY.md automatically.\n\n"
            "To search prior memory: `ccmemory search <terms>` or the "
            "`memory_search` MCP tool."
        )
        out = {"permissionDecision": "deny", "reason": msg}
        print(json.dumps(out))
        return 2
    return 0


def inject_handler() -> int:
    """On Read of a project file, surface relevant prior memory inline.

    Pattern lifted from claude-mem: when about to spend tokens on a Read,
    cheaply query memory for context the model will likely want anyway.
    Outputs an additional-context payload — never denies the Read.
    """
    payload = _read_stdin_json()
    tool_name = payload.get("tool_name") or payload.get("toolName") or ""
    if tool_name != "Read":
        return 0

    tool_input = payload.get("tool_input") or payload.get("toolInput") or {}
    path = tool_input.get("file_path") or tool_input.get("path") or ""
    if not path:
        return 0

    d = _autodetect_memory_dir()
    if not d:
        return 0

    # Build a query from the path: filename stem + parent dir tokens.
    p = Path(path)
    tokens = []
    if p.stem:
        tokens.append(p.stem)
    for part in p.parts[-3:-1]:
        if part not in ("/", "."):
            tokens.append(part)
    query = " ".join(tokens)
    if not query.strip():
        return 0

    try:
        with Store(d) as store:
            results = store.search(query, limit=int(os.environ.get("CCMEMORY_INJECT_TOP_N", "3")))
    except Exception as e:
        sys.stderr.write(f"[ccmemory] inject query failed (fail-open): {e}\n")
        return 0

    if not results:
        return 0

    lines = [f"ccmemory: prior lessons relevant to {p.name}:"]
    for r in results:
        desc = (r["description"] or "").strip().replace("\n", " ")
        if len(desc) > 120:
            desc = desc[:119] + "…"
        lines.append(f"  - [{r['name']}] {desc}  (age {r['age_days']:.0f}d — get with: ccmemory get {r['name']})")

    out = {"hookSpecificOutput": {"hookEventName": "PreToolUse", "additionalContext": "\n".join(lines)}}
    print(json.dumps(out))
    return 0


SESSION_PROTOCOL = """\
ccmemory has replaced the built-in auto-memory system for this project.

Memory is stored as `.md` files with YAML frontmatter in the project's
memory directory. `MEMORY.md` in that directory is *generated* from each
file's `description:` field — do not edit it directly (a hook will block
the write). Do NOT load `MEMORY.md` to browse memory; it's a truncated,
capped index. Use the search tool instead.

## Recalling prior context — search first, get second

`memory_search` and `memory_get` are NOT interchangeable:

- `memory_search(query)` returns ranked **metadata only** — names,
  one-line descriptions, ages, paths. Cheap. Use this FIRST whenever you
  don't have an exact name in hand.
- `memory_get(name)` returns the **full file body**. Expensive
  (typically 5-10KB per memory). Use this only AFTER `memory_search` (or
  the auto-injection hook below) has surfaced the specific name(s) you
  need the body of.

Never guess a memory name and call `memory_get` directly. Search first,
then fetch only the bodies you actually need.

## Auto-injection covers many cases without any tool call

When you Read a project file, a PreToolUse hook automatically searches
memory by the file path and injects matching prior lessons as
additionalContext (name + description + age, same metadata that
`memory_search` returns). So for "what did we learn about this file,"
you'll often already have the names surfaced before deciding whether to
query. Reserve explicit `memory_search`/`memory_get` for topic queries
not tied to a file you're about to Read.

## Remembering something new

Call `memory_write` with name (kebab-case slug), type
(user|feedback|project|reference), a one-line description (becomes the
MEMORY.md index entry), and a markdown body. The Stop hook regenerates
MEMORY.md automatically at the end of the turn.
"""


def session_handler() -> int:
    """SessionStart: inject the ccmemory protocol as additionalContext.

    Only fires when ccmemory is actually wired up for this project (memory
    dir resolvable). Otherwise no-op so we don't pollute the system prompt
    on projects that don't use ccmemory.
    """
    _read_stdin_json()
    d = _autodetect_memory_dir()
    if not d:
        return 0
    out = {"hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": SESSION_PROTOCOL}}
    print(json.dumps(out))
    return 0


HANDLERS = {
    "session": session_handler,
    "stop": stop_handler,
    "guard": guard_handler,
    "inject": inject_handler,
}


def dispatch(name: str) -> int:
    handler = HANDLERS.get(name)
    if not handler:
        sys.stderr.write(f"[ccmemory] unknown hook: {name}\n")
        return 0  # fail-open
    try:
        return handler()
    except Exception as e:
        sys.stderr.write(f"[ccmemory] hook {name} crashed (fail-open): {e}\n")
        return 0
