"""Hook handlers: guard denies, session injection, stop regen, fail-open."""

from __future__ import annotations

import io
import json

import pytest

from ccprospect import hooks, paths
from tests.conftest import file_prospect, touch


def run_hook(monkeypatch, payload) -> io.StringIO:
    """Arm stdin with the hook payload and capture stdout; the test then
    invokes the handler itself and inspects the captured buffer."""
    monkeypatch.setattr("sys.stdin", io.StringIO(json.dumps(payload) if payload else ""))
    out = io.StringIO()
    monkeypatch.setattr("sys.stdout", out)
    return out


# -- guard ---------------------------------------------------------------------

@pytest.mark.parametrize("path", [
    "/x/proj/.ccprospect/contracts/p-0001-thing.md",
    "/x/proj/.ccprospect/events.jsonl",
    "/x/proj/.ccprospect/PROSPECT.md",
])
def test_guard_blocks_record_files(monkeypatch, path):
    out = run_hook(monkeypatch,
                   {"tool_name": "Write", "tool_input": {"file_path": path}})
    assert hooks.guard_handler() == 2
    payload = json.loads(out.getvalue())
    assert payload["permissionDecision"] == "deny"
    assert "prospect_amend" in payload["reason"]


@pytest.mark.parametrize("path", [
    "/x/proj/.ccprospect/probe_state.json",
    "/x/proj/.ccprospect/.gitignore",
    "/x/proj/src/main.py",
    "/x/proj/.ccmemory/MEMORY.md",
])
def test_guard_allows_everything_else(monkeypatch, path):
    out = run_hook(monkeypatch,
                   {"tool_name": "Write", "tool_input": {"file_path": path}})
    assert hooks.guard_handler() == 0
    assert out.getvalue() == ""


def test_guard_ignores_non_edit_tools(monkeypatch):
    out = run_hook(monkeypatch,
                   {"tool_name": "Read",
                    "tool_input": {"file_path": "/x/.ccprospect/events.jsonl"}})
    assert hooks.guard_handler() == 0
    assert out.getvalue() == ""


# -- session --------------------------------------------------------------------

def test_session_silent_without_store(startup_dir, monkeypatch):
    out = run_hook(monkeypatch, {})
    assert hooks.session_handler() == 0
    assert out.getvalue() == ""


def test_session_injects_inbox_and_protocol(store, startup_dir, monkeypatch):
    file_prospect(store, title="check the flag",
                  predicate={"type": "path_exists", "path": "hook.flag"})
    touch(startup_dir, "hook.flag")

    out = run_hook(monkeypatch, {})
    assert hooks.session_handler() == 0
    payload = json.loads(out.getvalue())
    context = payload["hookSpecificOutput"]["additionalContext"]
    assert payload["hookSpecificOutput"]["hookEventName"] == "SessionStart"
    assert "PROSPECT INBOX: 1 fired" in context
    assert "p-0001" in context and "check the flag" in context
    assert "do the thing" in context  # the intention travels with the fire
    assert "ccprospect protocol" in context
    # session evaluation also refreshed the digest
    assert paths.index_path(store.prospect_dir).exists()


def test_session_aging_nudge_after_repeat_sessions(store, startup_dir, monkeypatch):
    file_prospect(store, predicate={"type": "path_exists", "path": "aged.flag"})
    touch(startup_dir, "aged.flag")

    out = run_hook(monkeypatch, {})
    hooks.session_handler()
    assert "unacknowledged across multiple sessions" not in out.getvalue()

    out = run_hook(monkeypatch, {})
    hooks.session_handler()
    assert "unacknowledged across multiple sessions" in out.getvalue()


def test_session_respects_no_probes(store, startup_dir, monkeypatch):
    file_prospect(store, title="cmd probe",
                  predicate={"type": "cmd_ok", "run": "test -f np.flag", "min_interval": 0})
    touch(startup_dir, "np.flag")

    monkeypatch.setenv("CCPROSPECT_NO_PROBES", "1")
    out = run_hook(monkeypatch, {})
    hooks.session_handler()
    assert "0 fired" in json.loads(out.getvalue())["hookSpecificOutput"]["additionalContext"]

    monkeypatch.delenv("CCPROSPECT_NO_PROBES")
    out = run_hook(monkeypatch, {})
    hooks.session_handler()
    assert "1 fired" in json.loads(out.getvalue())["hookSpecificOutput"]["additionalContext"]


# -- stop -------------------------------------------------------------------------

def test_stop_regenerates_digest(store, startup_dir, monkeypatch):
    file_prospect(store, title="digest me")
    run_hook(monkeypatch, {})
    assert hooks.stop_handler() == 0
    content = paths.index_path(store.prospect_dir).read_text(encoding="utf-8")
    assert "generated by ccprospect" in content
    assert "digest me" in content


def test_stop_silent_without_store(startup_dir, monkeypatch):
    run_hook(monkeypatch, {})
    assert hooks.stop_handler() == 0


def test_dispatch_unknown_hook_fails_open(monkeypatch):
    run_hook(monkeypatch, {})
    assert hooks.dispatch("nonsense") == 0
