"""PROSPECT.md generator — the human/diff-friendly digest.

Generated deterministically from derived state (like ccmemory's MEMORY.md
from frontmatter); the Stop hook regenerates it and a PreToolUse hook blocks
direct edits. It is a DIGEST for humans reading the repo — the model should
use prospect_inbox()/prospect_list(), not parse this file.
"""

from __future__ import annotations

from pathlib import Path

from .store import Store

DEFAULT_FILE_CAP = 12_000  # total bytes PROSPECT.md is allowed to reach
RESOLVED_SHOWN = 15


def generate(prospect_dir: Path) -> str:
    store = Store(prospect_dir)
    states = sorted(store.states().values(), key=lambda s: s.id)

    active = [st for st in states if st.active]
    fired = [st for st in states if st.attention == "fired"]
    closed = [st for st in states if st.attention == "closed"]

    out: list[str] = [
        "# PROSPECT — generated by ccprospect; do not edit",
        "",
        f"{len(active)} active · {len(fired)} fired awaiting ack · "
        f"{len(closed)} closed · {len(states)} total",
        "",
    ]

    def line(st) -> str:
        c = st.contract
        bits = [f"- **{c.id}** {c.title} — {c.predicate.get('type')}, expires {c.expires}"]
        if c.bucket is not None:
            bits.append(f"(bucket {c.bucket})")
        return " ".join(bits)

    if fired:
        out.append("## fired — awaiting acknowledgment")
        for st in fired:
            out.append(line(st) + f" — fired {st.fired_at}")
        out.append("")

    watching = [st for st in active if st.attention in ("open", "acked")]
    if watching:
        out.append("## watching")
        for st in watching:
            out.append(line(st))
        out.append("")

    deferred = [st for st in active if st.attention == "deferred"]
    if deferred:
        out.append("## deferred")
        for st in deferred:
            out.append(line(st) + f" — next review {st.next_review}")
        out.append("")

    if closed:
        out.append(f"## closed (last {RESOLVED_SHOWN})")
        for st in closed[-RESOLVED_SHOWN:]:
            c = st.contract
            suffix = st.resolution
            if st.resolved_counterfactually:
                suffix += " (counterfactual)"
            if st.successor:
                suffix += f" → {st.successor}"
            out.append(f"- {c.id} {c.title} — {suffix}")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def write(prospect_dir: Path, *, file_cap: int = DEFAULT_FILE_CAP) -> dict:
    content = generate(prospect_dir)
    truncated = False
    if len(content.encode("utf-8")) > file_cap:
        content = content.encode("utf-8")[:file_cap].decode("utf-8", errors="ignore")
        content = content.rsplit("\n", 1)[0] + "\n# [TRUNCATED — file_cap exceeded]\n"
        truncated = True
    target = Path(prospect_dir) / "PROSPECT.md"
    target.write_text(content, encoding="utf-8")
    return {"path": str(target), "bytes": len(content.encode("utf-8")), "truncated": truncated}
